extends:
  - "airbnb-base"
  - "jest"
env:
  node: true
plugins:
  - "eslint-plugin-import"
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: 0
